import type { Lang } from "./i18n.ts";

type T = Record<Lang, string>;
const w = (en: string, fr: string, de: string): T => ({ en, fr, de });

// Extra words for existing topics, merged after the current ones.
export const EXTRA_WORDS: Record<string, T[]> = {
  food: [
    w("Spaghetti", "Spaghetti", "Spaghetti"), w("Hamburger", "Hamburger", "Hamburger"), w("Hot dog", "Hot-dog", "Hotdog"),
    w("French fries", "Frites", "Pommes frites"), w("Apple", "Pomme", "Apfel"), w("Strawberry", "Fraise", "Erdbeere"),
    w("Watermelon", "Pastèque", "Wassermelone"), w("Pineapple", "Ananas", "Ananas"), w("Lemon", "Citron", "Zitrone"),
    w("Carrot", "Carotte", "Karotte"), w("Tomato", "Tomate", "Tomate"), w("Potato", "Pomme de terre", "Kartoffel"),
    w("Egg", "Œuf", "Ei"), w("Bread", "Pain", "Brot"), w("Honey", "Miel", "Honig"),
    w("Soup", "Soupe", "Suppe"), w("Salad", "Salade", "Salat"), w("Cake", "Gâteau", "Kuchen"),
    w("Cookie", "Biscuit", "Guetzli"), w("Waffle", "Gaufre", "Waffel"), w("Pretzel", "Bretzel", "Brezel"),
    w("Chicken", "Poulet", "Poulet"), w("Sausage", "Saucisse", "Wurst"), w("Rice", "Riz", "Reis"),
    w("Corn", "Maïs", "Mais"), w("Grapes", "Raisin", "Trauben"), w("Muesli", "Birchermuesli", "Birchermüesli"),
    w("Avocado", "Avocat", "Avocado"), w("Onion", "Oignon", "Zwiebel"), w("Cherry", "Cerise", "Kirsche"),
  ],
  places: [
    w("Museum", "Musée", "Museum"), w("Church", "Église", "Kirche"), w("Laundromat", "Laverie", "Waschsalon"),
    w("Restaurant", "Restaurant", "Restaurant"), w("Swimming pool", "Piscine", "Schwimmbad"), w("Playground", "Place de jeux", "Spielplatz"),
    w("Park", "Parc", "Park"), w("Stadium", "Stade", "Stadion"), w("Prison", "Prison", "Gefängnis"),
    w("Police station", "Poste de police", "Polizeiposten"), w("Post office", "Poste", "Post"), w("Bank", "Banque", "Bank"),
    w("Pharmacy", "Pharmacie", "Apotheke"), w("Gym", "Salle de sport", "Fitnessstudio"), w("Lighthouse", "Phare", "Leuchtturm"),
    w("Circus", "Cirque", "Zirkus"), w("Theatre", "Théâtre", "Theater"), w("Amusement park", "Parc d'attractions", "Freizeitpark"),
    w("Aquarium", "Aquarium", "Aquarium"), w("Bowling alley", "Bowling", "Bowlingbahn"), w("Petrol station", "Station-service", "Tankstelle"),
    w("Car wash", "Station de lavage", "Autowaschanlage"), w("Office", "Bureau", "Büro"), w("Factory", "Usine", "Fabrik"),
    w("Harbour", "Port", "Hafen"), w("Cemetery", "Cimetière", "Friedhof"), w("Mountain hut", "Cabane de montagne", "Berghütte"),
    w("Kindergarten", "École enfantine", "Kindergarten"), w("University", "Université", "Universität"), w("Ice rink", "Patinoire", "Eisbahn"),
  ],
  animals: [
    w("Giraffe", "Girafe", "Giraffe"), w("Zebra", "Zèbre", "Zebra"), w("Monkey", "Singe", "Affe"),
    w("Tiger", "Tigre", "Tiger"), w("Bear", "Ours", "Bär"), w("Wolf", "Loup", "Wolf"),
    w("Fox", "Renard", "Fuchs"), w("Rabbit", "Lapin", "Kaninchen"), w("Frog", "Grenouille", "Frosch"),
    w("Crocodile", "Crocodile", "Krokodil"), w("Hippo", "Hippopotame", "Nilpferd"), w("Rhino", "Rhinocéros", "Nashorn"),
    w("Camel", "Chameau", "Kamel"), w("Parrot", "Perroquet", "Papagei"), w("Eagle", "Aigle", "Adler"),
    w("Flamingo", "Flamant rose", "Flamingo"), w("Turtle", "Tortue", "Schildkröte"), w("Bee", "Abeille", "Biene"),
    w("Butterfly", "Papillon", "Schmetterling"), w("Spider", "Araignée", "Spinne"), w("Snail", "Escargot", "Schnecke"),
    w("Hedgehog", "Hérisson", "Igel"), w("Bat", "Chauve-souris", "Fledermaus"), w("Koala", "Koala", "Koala"),
    w("Panda", "Panda", "Panda"), w("Gorilla", "Gorille", "Gorilla"), w("Ibex", "Bouquetin", "Steinbock"),
    w("Marmot", "Marmotte", "Murmeltier"), w("Cat", "Chat", "Katze"), w("Dog", "Chien", "Hund"),
  ],
  objects: [
    w("Key", "Clé", "Schlüssel"), w("Alarm clock", "Réveil", "Wecker"), w("Wallet", "Portefeuille", "Portemonnaie"),
    w("Book", "Livre", "Buch"), w("Camera", "Appareil photo", "Kamera"), w("Smartphone", "Smartphone", "Handy"),
    w("Laptop", "Ordinateur portable", "Laptop"), w("Television", "Télévision", "Fernseher"), w("Hairdryer", "Sèche-cheveux", "Föhn"),
    w("Comb", "Peigne", "Kamm"), w("Soap", "Savon", "Seife"), w("Towel", "Serviette", "Badetuch"),
    w("Teddy bear", "Ours en peluche", "Teddybär"), w("Dice", "Dé", "Würfel"), w("Coin", "Pièce de monnaie", "Münze"),
    w("Magnifying glass", "Loupe", "Lupe"), w("Flashlight", "Lampe de poche", "Taschenlampe"), w("Compass", "Boussole", "Kompass"),
    w("Padlock", "Cadenas", "Vorhängeschloss"), w("Envelope", "Enveloppe", "Briefumschlag"), w("Calendar", "Calendrier", "Kalender"),
    w("Bucket", "Seau", "Eimer"), w("Broom", "Balai", "Besen"), w("Light bulb", "Ampoule", "Glühbirne"),
    w("Battery", "Pile", "Batterie"), w("Paintbrush", "Pinceau", "Pinsel"), w("Needle", "Aiguille", "Nadel"),
    w("Rope", "Corde", "Seil"), w("Basket", "Panier", "Korb"), w("Vase", "Vase", "Vase"),
  ],
  jobs: [
    w("Doctor", "Médecin", "Arzt"), w("Nurse", "Infirmière", "Pflegefachfrau"), w("Police officer", "Policier", "Polizist"),
    w("Train driver", "Conducteur de train", "Lokführer"), w("Butcher", "Boucher", "Metzger"), w("Plumber", "Plombier", "Sanitär"),
    w("Electrician", "Électricien", "Elektriker"), w("Carpenter", "Menuisier", "Schreiner"), w("Mechanic", "Mécanicien", "Mechaniker"),
    w("Postman", "Facteur", "Pöstler"), w("Vet", "Vétérinaire", "Tierarzt"), w("Judge", "Juge", "Richter"),
    w("Singer", "Chanteur", "Sänger"), w("Actor", "Acteur", "Schauspieler"), w("Lumberjack", "Bûcheron", "Holzfäller"),
    w("Flight attendant", "Hôtesse de l'air", "Flugbegleiterin"), w("Journalist", "Journaliste", "Journalist"), w("Scientist", "Scientifique", "Wissenschaftler"),
    w("Architect", "Architecte", "Architekt"), w("Waiter", "Serveur", "Kellner"), w("Cashier", "Caissier", "Kassierer"),
    w("Bus driver", "Chauffeur de bus", "Buschauffeur"), w("Florist", "Fleuriste", "Florist"), w("Tailor", "Tailleur", "Schneider"),
    w("Soldier", "Soldat", "Soldat"), w("Lifeguard", "Maître-nageur", "Bademeister"), w("Clown", "Clown", "Clown"),
    w("Programmer", "Programmeur", "Programmierer"), w("Builder", "Maçon", "Maurer"), w("Chimney sweep", "Ramoneur", "Kaminfeger"),
  ],
  sports: [
    w("Basketball", "Basketball", "Basketball"), w("Volleyball", "Volleyball", "Volleyball"), w("Handball", "Handball", "Handball"),
    w("Badminton", "Badminton", "Badminton"), w("Table tennis", "Ping-pong", "Tischtennis"), w("Marathon", "Marathon", "Marathon"),
    w("Rowing", "Aviron", "Rudern"), w("Surfing", "Surf", "Surfen"), w("Horse riding", "Équitation", "Reiten"),
    w("Judo", "Judo", "Judo"), w("Karate", "Karaté", "Karate"), w("Fencing", "Escrime", "Fechten"),
    w("Archery", "Tir à l'arc", "Bogenschiessen"), w("Gymnastics", "Gymnastique", "Turnen"), w("Snowboarding", "Snowboard", "Snowboarden"),
    w("Ice skating", "Patinage", "Eislaufen"), w("Curling", "Curling", "Curling"), w("Rugby", "Rugby", "Rugby"),
    w("Baseball", "Baseball", "Baseball"), w("Bungee jumping", "Saut à l'élastique", "Bungee-Jumping"), w("Triathlon", "Triathlon", "Triathlon"),
    w("Cross-country skiing", "Ski de fond", "Langlauf"), w("Ski jumping", "Saut à ski", "Skispringen"), w("Bobsleigh", "Bobsleigh", "Bob"),
    w("Mountain biking", "VTT", "Mountainbiken"), w("Darts", "Fléchettes", "Darts"), w("Water polo", "Water-polo", "Wasserball"),
    w("Pole vault", "Saut à la perche", "Stabhochsprung"), w("Sumo", "Sumo", "Sumo"), w("Paragliding", "Parapente", "Gleitschirmfliegen"),
  ],
  movies: [
    w("Finding Nemo", "Le Monde de Nemo", "Findet Nemo"), w("The Little Mermaid", "La Petite Sirène", "Arielle, die Meerjungfrau"), w("Cinderella", "Cendrillon", "Cinderella"),
    w("Snow White", "Blanche-Neige", "Schneewittchen"), w("Aladdin", "Aladdin", "Aladdin"), w("Spider-Man", "Spider-Man", "Spider-Man"),
    w("Superman", "Superman", "Superman"), w("Mickey Mouse", "Mickey Mouse", "Micky Maus"), w("SpongeBob", "Bob l'éponge", "SpongeBob"),
    w("Pokémon", "Pokémon", "Pokémon"), w("Minions", "Les Minions", "Minions"), w("Ghostbusters", "SOS Fantômes", "Ghostbusters"),
    w("Ratatouille", "Ratatouille", "Ratatouille"), w("Up", "Là-haut", "Oben"), w("Monsters, Inc.", "Monstres & Cie", "Die Monster AG"),
    w("The Incredibles", "Les Indestructibles", "Die Unglaublichen"), w("Ice Age", "L'Âge de glace", "Ice Age"), w("Madagascar", "Madagascar", "Madagascar"),
    w("Kung Fu Panda", "Kung Fu Panda", "Kung Fu Panda"), w("Despicable Me", "Moi, moche et méchant", "Ich – Einfach unverbesserlich"), w("The Smurfs", "Les Schtroumpfs", "Die Schlümpfe"),
    w("Peppa Pig", "Peppa Pig", "Peppa Wutz"), w("Heidi", "Heidi", "Heidi"), w("Pinocchio", "Pinocchio", "Pinocchio"),
    w("Mary Poppins", "Mary Poppins", "Mary Poppins"), w("James Bond", "James Bond", "James Bond"), w("Indiana Jones", "Indiana Jones", "Indiana Jones"),
    w("Home Alone", "Maman, j'ai raté l'avion", "Kevin – Allein zu Haus"), w("Pirates of the Caribbean", "Pirates des Caraïbes", "Fluch der Karibik"), w("The Jungle Book", "Le Livre de la jungle", "Das Dschungelbuch"),
  ],
  travel: [
    w("Map", "Carte", "Landkarte"), w("Ticket", "Billet", "Billett"), w("Boarding pass", "Carte d'embarquement", "Bordkarte"),
    w("Travel adapter", "Adaptateur de voyage", "Reiseadapter"), w("Guidebook", "Guide de voyage", "Reiseführer"), w("Jet lag", "Décalage horaire", "Jetlag"),
    w("Youth hostel", "Auberge de jeunesse", "Jugendherberge"), w("Travel pillow", "Coussin de voyage", "Nackenkissen"), w("Customs", "Douane", "Zoll"),
    w("Border", "Frontière", "Grenze"), w("Visa", "Visa", "Visum"), w("Currency exchange", "Bureau de change", "Wechselstube"),
    w("Tour guide", "Guide touristique", "Reiseleiter"), w("Flip-flops", "Tongs", "Flipflops"), w("Selfie stick", "Perche à selfie", "Selfiestick"),
    w("Check-in", "Enregistrement", "Check-in"), w("Travel agency", "Agence de voyages", "Reisebüro"), w("Hitchhiking", "Auto-stop", "Autostopp"),
    w("Eiffel Tower", "Tour Eiffel", "Eiffelturm"), w("Statue of Liberty", "Statue de la Liberté", "Freiheitsstatue"), w("Pyramids", "Pyramides", "Pyramiden"),
    w("Great Wall of China", "Grande Muraille de Chine", "Chinesische Mauer"), w("Colosseum", "Colisée", "Kolosseum"), w("Leaning Tower of Pisa", "Tour de Pise", "Schiefer Turm von Pisa"),
    w("Big Ben", "Big Ben", "Big Ben"), w("Taj Mahal", "Taj Mahal", "Taj Mahal"), w("Motorhome", "Camping-car", "Wohnmobil"),
    w("Honeymoon", "Lune de miel", "Flitterwochen"), w("Sleeping bag", "Sac de couchage", "Schlafsack"), w("Backpacker", "Routard", "Rucksacktourist"),
  ],
  music: [
    w("Flute", "Flûte", "Flöte"), w("Saxophone", "Saxophone", "Saxofon"), w("Cello", "Violoncelle", "Cello"),
    w("Harp", "Harpe", "Harfe"), w("Accordion", "Accordéon", "Handorgel"), w("Harmonica", "Harmonica", "Mundharmonika"),
    w("Xylophone", "Xylophone", "Xylofon"), w("Tambourine", "Tambourin", "Tamburin"), w("Triangle", "Triangle", "Triangel"),
    w("Trombone", "Trombone", "Posaune"), w("Clarinet", "Clarinette", "Klarinette"), w("Tuba", "Tuba", "Tuba"),
    w("Bass guitar", "Basse", "Bassgitarre"), w("Synthesizer", "Synthétiseur", "Synthesizer"), w("Orchestra", "Orchestre", "Orchester"),
    w("Conductor", "Chef d'orchestre", "Dirigent"), w("Band", "Groupe de musique", "Band"), w("Lullaby", "Berceuse", "Schlaflied"),
    w("National anthem", "Hymne national", "Nationalhymne"), w("Vinyl record", "Disque vinyle", "Schallplatte"), w("Loudspeaker", "Haut-parleur", "Lautsprecher"),
    w("Music box", "Boîte à musique", "Spieldose"), w("Sheet music", "Partition", "Noten"), w("Stage", "Scène", "Bühne"),
    w("Encore", "Rappel", "Zugabe"), w("Rock star", "Rock star", "Rockstar"), w("Radio", "Radio", "Radio"),
    w("Bagpipes", "Cornemuse", "Dudelsack"),
  ],
  swiss: [
    w("Swiss flag", "Drapeau suisse", "Schweizerfahne"), w("Swiss wrestling", "Lutte suisse", "Schwingen"), w("Emmental", "Emmental", "Emmentaler"),
    w("Gruyère", "Gruyère", "Greyerzer"), w("Chalet", "Chalet", "Chalet"), w("St. Bernard dog", "Saint-Bernard", "Bernhardiner"),
    w("Rhine Falls", "Chutes du Rhin", "Rheinfall"), w("Chapel Bridge", "Pont de la Chapelle", "Kapellbrücke"), w("Federal Palace", "Palais fédéral", "Bundeshaus"),
    w("William Tell", "Guillaume Tell", "Wilhelm Tell"), w("Zopf bread", "Tresse", "Zopf"), w("Alpine macaroni", "Macaronis du chalet", "Älplermagronen"),
    w("Läckerli", "Leckerli", "Läckerli"), w("Meringue", "Meringue", "Meringue"), w("Swiss franc", "Franc suisse", "Schweizer Franken"),
    w("Alpine pasture", "Alpage", "Alp"), w("Flag throwing", "Lancer de drapeau", "Fahnenschwingen"), w("Hornussen", "Hornuss", "Hornussen"),
    w("Jass", "Jass", "Jassen"), w("Carnival", "Carnaval", "Fasnacht"), w("Swiss National Day", "Fête nationale", "Bundesfeier"),
    w("Glacier Express", "Glacier Express", "Glacier Express"), w("Gotthard Tunnel", "Tunnel du Gothard", "Gotthardtunnel"), w("Postbus", "Car postal", "Postauto"),
    w("Edelweiss", "Edelweiss", "Edelweiss"), w("Cuckoo clock", "Horloge à coucou", "Kuckucksuhr"), w("Lake Lucerne", "Lac des Quatre-Cantons", "Vierwaldstättersee"),
    w("Eiger", "Eiger", "Eiger"),
  ],
  home: [
    w("Bed", "Lit", "Bett"), w("Wardrobe", "Armoire", "Kleiderschrank"), w("Curtain", "Rideau", "Vorhang"),
    w("Carpet", "Tapis", "Teppich"), w("Lamp", "Lampe", "Lampe"), w("Bookshelf", "Étagère", "Büchergestell"),
    w("Toilet", "Toilettes", "WC"), w("Shower", "Douche", "Dusche"), w("Sink", "Lavabo", "Lavabo"),
    w("Attic", "Grenier", "Estrich"), w("Basement", "Cave", "Keller"), w("Garage", "Garage", "Garage"),
    w("Fireplace", "Cheminée", "Cheminée"), w("Window", "Fenêtre", "Fenster"), w("Front door", "Porte d'entrée", "Haustür"),
    w("Radiator", "Radiateur", "Heizkörper"), w("Doormat", "Paillasson", "Fussmatte"), w("Laundry basket", "Panier à linge", "Wäschekorb"),
    w("Ironing board", "Planche à repasser", "Bügelbrett"), w("Clothes hanger", "Cintre", "Kleiderbügel"), w("Armchair", "Fauteuil", "Sessel"),
    w("Rocking chair", "Chaise à bascule", "Schaukelstuhl"), w("Bunk bed", "Lits superposés", "Kajütenbett"), w("Nightstand", "Table de nuit", "Nachttisch"),
    w("Houseplant", "Plante d'intérieur", "Zimmerpflanze"), w("Smoke detector", "Détecteur de fumée", "Rauchmelder"), w("Light switch", "Interrupteur", "Lichtschalter"),
    w("Picture frame", "Cadre photo", "Bilderrahmen"),
  ],
  nature: [
    w("Mountain", "Montagne", "Berg"), w("River", "Rivière", "Fluss"), w("Lake", "Lac", "See"),
    w("Tree", "Arbre", "Baum"), w("Cliff", "Falaise", "Klippe"), w("Valley", "Vallée", "Tal"),
    w("Meadow", "Prairie", "Wiese"), w("Swamp", "Marais", "Sumpf"), w("Jungle", "Jungle", "Dschungel"),
    w("Canyon", "Canyon", "Canyon"), w("Sand dune", "Dune", "Düne"), w("Geyser", "Geyser", "Geysir"),
    w("Hill", "Colline", "Hügel"), w("Pine cone", "Pomme de pin", "Tannzapfen"), w("Acorn", "Gland", "Eichel"),
    w("Leaf", "Feuille", "Blatt"), w("Moss", "Mousse", "Moos"), w("Stone", "Pierre", "Stein"),
    w("Stream", "Ruisseau", "Bach"), w("Pond", "Étang", "Teich"), w("Oasis", "Oasis", "Oase"),
    w("Iceberg", "Iceberg", "Eisberg"), w("Earthquake", "Tremblement de terre", "Erdbeben"), w("Northern lights", "Aurore boréale", "Polarlicht"),
    w("Feather", "Plume", "Feder"), w("Nest", "Nid", "Nest"), w("Cactus", "Cactus", "Kaktus"),
    w("Palm tree", "Palmier", "Palme"),
  ],
  transport: [
    w("Airplane", "Avion", "Flugzeug"), w("Bus", "Bus", "Bus"), w("Motorbike", "Moto", "Motorrad"),
    w("Truck", "Camion", "Lastwagen"), w("Fire engine", "Camion de pompiers", "Feuerwehrauto"), w("Police car", "Voiture de police", "Polizeiauto"),
    w("Car", "Voiture", "Auto"), w("Subway", "Métro", "U-Bahn"), w("Ferry", "Ferry", "Fähre"),
    w("Canoe", "Canoë", "Kanu"), w("Pedal boat", "Pédalo", "Pedalo"), w("Speedboat", "Hors-bord", "Motorboot"),
    w("Jet ski", "Jet-ski", "Jetski"), w("Quad bike", "Quad", "Quad"), w("Chairlift", "Télésiège", "Sessellift"),
    w("Funicular", "Funiculaire", "Standseilbahn"), w("Steam train", "Train à vapeur", "Dampfzug"), w("Limousine", "Limousine", "Stretchlimousine"),
    w("Glider", "Planeur", "Segelflugzeug"), w("Zeppelin", "Zeppelin", "Zeppelin"), w("Unicycle", "Monocycle", "Einrad"),
    w("Tandem", "Tandem", "Tandem"), w("Rollerblades", "Rollers", "Inlineskates"), w("Sled", "Luge", "Schlitten"),
    w("Snowmobile", "Motoneige", "Schneemobil"), w("Tow truck", "Dépanneuse", "Abschleppwagen"), w("Garbage truck", "Camion-poubelle", "Kehrichtwagen"),
    w("Excavator", "Pelleteuse", "Bagger"),
  ],
  fantasy: [
    w("Fairy", "Fée", "Fee"), w("Giant", "Géant", "Riese"), w("Dwarf", "Nain", "Zwerg"),
    w("Elf", "Elfe", "Elfe"), w("Troll", "Troll", "Troll"), w("Goblin", "Gobelin", "Kobold"),
    w("Zombie", "Zombie", "Zombie"), w("Werewolf", "Loup-garou", "Werwolf"), w("Mummy", "Momie", "Mumie"),
    w("Phoenix", "Phénix", "Phönix"), w("Griffin", "Griffon", "Greif"), w("Centaur", "Centaure", "Zentaur"),
    w("Pegasus", "Pégase", "Pegasus"), w("Cyclops", "Cyclope", "Zyklop"), w("Genie", "Génie", "Flaschengeist"),
    w("Magic wand", "Baguette magique", "Zauberstab"), w("Flying carpet", "Tapis volant", "Fliegender Teppich"), w("Crystal ball", "Boule de cristal", "Kristallkugel"),
    w("Potion", "Potion", "Zaubertrank"), w("Spell book", "Grimoire", "Zauberbuch"), w("Superhero", "Super-héros", "Superheld"),
    w("Ninja", "Ninja", "Ninja"), w("Invisibility cloak", "Cape d'invisibilité", "Tarnumhang"), w("Yeti", "Yéti", "Yeti"),
    w("Loch Ness monster", "Monstre du Loch Ness", "Ungeheuer von Loch Ness"), w("Minotaur", "Minotaure", "Minotaurus"), w("Princess", "Princesse", "Prinzessin"),
    w("Crown", "Couronne", "Krone"),
  ],
  clothes: [
    w("T-shirt", "T-shirt", "T-Shirt"), w("Jeans", "Jean", "Jeans"), w("Dress", "Robe", "Kleid"),
    w("Skirt", "Jupe", "Jupe"), w("Socks", "Chaussettes", "Socken"), w("Sneakers", "Baskets", "Turnschuhe"),
    w("Boots", "Bottes", "Stiefel"), w("Sandals", "Sandales", "Sandalen"), w("Hat", "Chapeau", "Hut"),
    w("Hoodie", "Sweat à capuche", "Hoodie"), w("Sweater", "Pull", "Pullover"), w("Down jacket", "Doudoune", "Daunenjacke"),
    w("Coat", "Manteau", "Mantel"), w("Suit", "Costume", "Anzug"), w("Shirt", "Chemise", "Hemd"),
    w("Shorts", "Short", "Shorts"), w("Underpants", "Slip", "Unterhose"), w("Bathrobe", "Peignoir", "Bademantel"),
    w("Tracksuit", "Survêtement", "Trainingsanzug"), w("Bow tie", "Nœud papillon", "Fliege"), w("Uniform", "Uniforme", "Uniform"),
    w("Handbag", "Sac à main", "Handtasche"), w("Earrings", "Boucles d'oreilles", "Ohrringe"), w("Necklace", "Collier", "Halskette"),
    w("Ring", "Bague", "Ring"), w("Helmet", "Casque", "Helm"), w("Poncho", "Poncho", "Poncho"),
    w("Overalls", "Salopette", "Latzhose"),
  ],
  hobbies: [
    w("Reading", "Lecture", "Lesen"), w("Scrapbooking", "Scrapbooking", "Scrapbooking"), w("Sewing", "Couture", "Nähen"),
    w("Pottery", "Poterie", "Töpfern"), w("Origami", "Origami", "Origami"), w("Board games", "Jeux de société", "Brettspiele"),
    w("Hiking", "Randonnée", "Wandern"), w("Bird watching", "Observation des oiseaux", "Vogelbeobachtung"), w("Stamp collecting", "Philatélie", "Briefmarkensammeln"),
    w("Crossword", "Mots croisés", "Kreuzworträtsel"), w("Sudoku", "Sudoku", "Sudoku"), w("Drawing", "Dessin", "Zeichnen"),
    w("Juggling", "Jonglage", "Jonglieren"), w("Model railway", "Train miniature", "Modelleisenbahn"), w("Crochet", "Crochet", "Häkeln"),
    w("Calligraphy", "Calligraphie", "Kalligrafie"), w("Geocaching", "Géocaching", "Geocaching"), w("Kite flying", "Cerf-volant", "Drachensteigen"),
    w("Beekeeping", "Apiculture", "Imkern"), w("Diary", "Journal intime", "Tagebuch"), w("Go-kart", "Karting", "Gokart"),
    w("Escape room", "Escape game", "Escape-Room"), w("Mini golf", "Minigolf", "Minigolf"), w("Trampoline", "Trampoline", "Trampolin"),
    w("Soap bubbles", "Bulles de savon", "Seifenblasen"), w("Podcast", "Podcast", "Podcast"), w("Playing cards", "Cartes à jouer", "Spielkarten"),
    w("Dominoes", "Dominos", "Domino"),
  ],
};

// Brand-new topics. `icon` is a lucide-react icon component name.
export const NEW_TOPICS: { id: string; icon: string; name: T; words: T[] }[] = [
  {
    id: "body", icon: "PersonStanding",
    name: w("Body", "Corps", "Körper"),
    words: [
      w("Head", "Tête", "Kopf"), w("Eye", "Œil", "Auge"), w("Nose", "Nez", "Nase"), w("Ear", "Oreille", "Ohr"),
      w("Mouth", "Bouche", "Mund"), w("Tooth", "Dent", "Zahn"), w("Tongue", "Langue", "Zunge"), w("Lips", "Lèvres", "Lippen"),
      w("Hair", "Cheveux", "Haare"), w("Beard", "Barbe", "Bart"), w("Moustache", "Moustache", "Schnurrbart"), w("Eyebrow", "Sourcil", "Augenbraue"),
      w("Eyelash", "Cil", "Wimper"), w("Chin", "Menton", "Kinn"), w("Cheek", "Joue", "Wange"), w("Forehead", "Front", "Stirn"),
      w("Neck", "Cou", "Hals"), w("Shoulder", "Épaule", "Schulter"), w("Arm", "Bras", "Arm"), w("Elbow", "Coude", "Ellbogen"),
      w("Hand", "Main", "Hand"), w("Finger", "Doigt", "Finger"), w("Thumb", "Pouce", "Daumen"), w("Fingernail", "Ongle", "Fingernagel"),
      w("Belly button", "Nombril", "Bauchnabel"), w("Stomach", "Ventre", "Bauch"), w("Back", "Dos", "Rücken"), w("Knee", "Genou", "Knie"),
      w("Foot", "Pied", "Fuss"), w("Toe", "Orteil", "Zehe"), w("Heel", "Talon", "Ferse"), w("Ankle", "Cheville", "Knöchel"),
      w("Heart", "Cœur", "Herz"), w("Brain", "Cerveau", "Gehirn"), w("Lungs", "Poumons", "Lunge"), w("Bone", "Os", "Knochen"),
      w("Muscle", "Muscle", "Muskel"), w("Skin", "Peau", "Haut"), w("Blood", "Sang", "Blut"), w("Freckles", "Taches de rousseur", "Sommersprossen"),
    ],
  },
  {
    id: "weather", icon: "CloudSun",
    name: w("Weather & seasons", "Météo & saisons", "Wetter & Jahreszeiten"),
    words: [
      w("Rain", "Pluie", "Regen"), w("Snow", "Neige", "Schnee"), w("Hail", "Grêle", "Hagel"), w("Fog", "Brouillard", "Nebel"),
      w("Wind", "Vent", "Wind"), w("Lightning", "Éclair", "Blitz"), w("Thunder", "Tonnerre", "Donner"), w("Cloud", "Nuage", "Wolke"),
      w("Sun", "Soleil", "Sonne"), w("Storm", "Tempête", "Sturm"), w("Tornado", "Tornade", "Tornado"), w("Hurricane", "Ouragan", "Hurrikan"),
      w("Heatwave", "Canicule", "Hitzewelle"), w("Frost", "Gel", "Frost"), w("Drizzle", "Bruine", "Nieselregen"), w("Puddle", "Flaque", "Pfütze"),
      w("Thermometer", "Thermomètre", "Thermometer"), w("Weather forecast", "Prévisions météo", "Wetterbericht"), w("Snowman", "Bonhomme de neige", "Schneemann"), w("Icicle", "Stalactite de glace", "Eiszapfen"),
      w("Dew", "Rosée", "Tau"), w("Avalanche", "Avalanche", "Lawine"), w("Flood", "Inondation", "Überschwemmung"), w("Drought", "Sécheresse", "Dürre"),
      w("Breeze", "Brise", "Brise"), w("Rain boots", "Bottes de pluie", "Gummistiefel"), w("Weather vane", "Girouette", "Wetterfahne"), w("Snowball", "Boule de neige", "Schneeball"),
      w("Sunburn", "Coup de soleil", "Sonnenbrand"), w("Spring", "Printemps", "Frühling"), w("Summer", "Été", "Sommer"), w("Autumn", "Automne", "Herbst"),
      w("Winter", "Hiver", "Winter"), w("Sleet", "Neige fondue", "Schneeregen"), w("Sandstorm", "Tempête de sable", "Sandsturm"), w("Wind turbine", "Éolienne", "Windrad"),
      w("Barometer", "Baromètre", "Barometer"), w("Monsoon", "Mousson", "Monsun"), w("Blizzard", "Blizzard", "Schneesturm"), w("Black ice", "Verglas", "Glatteis"),
    ],
  },
  {
    id: "kitchen", icon: "CookingPot",
    name: w("Kitchen", "Cuisine", "Küche"),
    words: [
      w("Frying pan", "Poêle", "Bratpfanne"), w("Saucepan", "Casserole", "Kochtopf"), w("Spatula", "Spatule", "Pfannenwender"), w("Whisk", "Fouet", "Schwingbesen"),
      w("Rolling pin", "Rouleau à pâtisserie", "Wallholz"), w("Cutting board", "Planche à découper", "Schneidebrett"), w("Knife", "Couteau", "Messer"), w("Fork", "Fourchette", "Gabel"),
      w("Spoon", "Cuillère", "Löffel"), w("Plate", "Assiette", "Teller"), w("Bowl", "Bol", "Schüssel"), w("Cup", "Tasse", "Tasse"),
      w("Glass", "Verre", "Glas"), w("Toaster", "Grille-pain", "Toaster"), w("Microwave", "Micro-ondes", "Mikrowelle"), w("Blender", "Mixeur", "Mixer"),
      w("Dishwasher", "Lave-vaisselle", "Geschirrspüler"), w("Coffee machine", "Machine à café", "Kaffeemaschine"), w("Grater", "Râpe", "Reibe"), w("Colander", "Passoire", "Sieb"),
      w("Ladle", "Louche", "Schöpfkelle"), w("Apron", "Tablier", "Schürze"), w("Oven mitt", "Gant de cuisine", "Topflappen"), w("Freezer", "Congélateur", "Tiefkühler"),
      w("Teapot", "Théière", "Teekanne"), w("Corkscrew", "Tire-bouchon", "Korkenzieher"), w("Can opener", "Ouvre-boîte", "Büchsenöffner"), w("Salt shaker", "Salière", "Salzstreuer"),
      w("Pepper mill", "Moulin à poivre", "Pfeffermühle"), w("Kitchen scale", "Balance de cuisine", "Küchenwaage"), w("Egg timer", "Minuteur", "Eieruhr"), w("Chopsticks", "Baguettes", "Stäbchen"),
      w("Aluminium foil", "Papier aluminium", "Alufolie"), w("Dish towel", "Torchon", "Geschirrtuch"), w("Sponge", "Éponge", "Schwamm"), w("Stove", "Plaque de cuisson", "Herd"),
      w("Pressure cooker", "Cocotte-minute", "Dampfkochtopf"), w("Thermos", "Thermos", "Thermoskanne"), w("Jar", "Bocal", "Einmachglas"), w("Tray", "Plateau", "Tablett"),
    ],
  },
  {
    id: "school", icon: "School",
    name: w("Classroom", "En classe", "Im Schulzimmer"),
    words: [
      w("Pencil", "Crayon", "Bleistift"), w("Pen", "Stylo", "Kugelschreiber"), w("Eraser", "Gomme", "Radiergummi"), w("Ruler", "Règle", "Lineal"),
      w("Sharpener", "Taille-crayon", "Spitzer"), w("Exercise book", "Cahier", "Heft"), w("Blackboard", "Tableau noir", "Wandtafel"), w("Chalk", "Craie", "Kreide"),
      w("School bag", "Cartable", "Schulthek"), w("Pencil case", "Trousse", "Etui"), w("Glue stick", "Bâton de colle", "Leimstift"), w("Calculator", "Calculatrice", "Taschenrechner"),
      w("Globe", "Globe", "Globus"), w("Homework", "Devoirs", "Hausaufgaben"), w("Exam", "Examen", "Prüfung"), w("Report card", "Bulletin scolaire", "Zeugnis"),
      w("Timetable", "Horaire", "Stundenplan"), w("Recess", "Récréation", "Pause"), w("Sports day", "Journée sportive", "Sporttag"), w("Principal", "Directeur d'école", "Schulleiter"),
      w("Classmate", "Camarade de classe", "Klassenkamerad"), w("Desk", "Pupitre", "Schulbank"), w("Alphabet", "Alphabet", "Alphabet"), w("Dictionary", "Dictionnaire", "Wörterbuch"),
      w("Atlas", "Atlas", "Atlas"), w("Protractor", "Rapporteur", "Winkelmesser"), w("Highlighter", "Surligneur", "Leuchtstift"), w("Felt-tip pen", "Feutre", "Filzstift"),
      w("School bus", "Bus scolaire", "Schulbus"), w("Lunchbox", "Boîte à goûter", "Znünibox"), w("School trip", "Course d'école", "Schulreise"), w("School bell", "Cloche de l'école", "Schulglocke"),
      w("Math", "Mathématiques", "Mathematik"), w("Sticker", "Autocollant", "Kleber"), w("Microscope", "Microscope", "Mikroskop"), w("Janitor", "Concierge", "Hauswart"),
      w("Detention", "Retenue", "Nachsitzen"), w("Dictation", "Dictée", "Diktat"), w("Stapler", "Agrafeuse", "Heftmaschine"), w("Class photo", "Photo de classe", "Klassenfoto"),
    ],
  },
  {
    id: "city", icon: "Building2",
    name: w("City", "Ville", "Stadt"),
    words: [
      w("Traffic light", "Feu rouge", "Ampel"), w("Crosswalk", "Passage piéton", "Fussgängerstreifen"), w("Skyscraper", "Gratte-ciel", "Wolkenkratzer"), w("Bus stop", "Arrêt de bus", "Bushaltestelle"),
      w("Fountain", "Fontaine", "Brunnen"), w("Bench", "Banc", "Parkbank"), w("Streetlamp", "Lampadaire", "Strassenlaterne"), w("Roundabout", "Rond-point", "Kreisel"),
      w("Parking garage", "Parking", "Parkhaus"), w("Sidewalk", "Trottoir", "Trottoir"), w("Bridge", "Pont", "Brücke"), w("Tunnel", "Tunnel", "Tunnel"),
      w("Statue", "Statue", "Statue"), w("Graffiti", "Graffiti", "Graffiti"), w("Manhole", "Bouche d'égout", "Schachtdeckel"), w("Billboard", "Panneau publicitaire", "Plakatwand"),
      w("Trash can", "Poubelle", "Abfalleimer"), w("Escalator", "Escalator", "Rolltreppe"), w("Elevator", "Ascenseur", "Lift"), w("Mailbox", "Boîte aux lettres", "Briefkasten"),
      w("Parking meter", "Parcomètre", "Parkuhr"), w("Market square", "Place du marché", "Marktplatz"), w("Construction site", "Chantier", "Baustelle"), w("Crane", "Grue", "Kran"),
      w("Pedestrian zone", "Zone piétonne", "Fussgängerzone"), w("Town hall", "Hôtel de ville", "Rathaus"), w("Kiosk", "Kiosque", "Kiosk"), w("Traffic jam", "Embouteillage", "Stau"),
      w("Cycle lane", "Piste cyclable", "Velostreifen"), w("Pigeon", "Pigeon", "Taube"), w("Apartment building", "Immeuble", "Wohnblock"), w("Street sign", "Panneau de signalisation", "Verkehrsschild"),
      w("Street musician", "Musicien de rue", "Strassenmusiker"), w("Food truck", "Food truck", "Foodtruck"), w("Fire hydrant", "Bouche d'incendie", "Hydrant"), w("Shopping mall", "Centre commercial", "Einkaufszentrum"),
      w("Flea market", "Marché aux puces", "Flohmarkt"), w("Neon sign", "Enseigne lumineuse", "Leuchtreklame"), w("Rooftop", "Toit", "Dach"), w("Skyline", "Skyline", "Skyline"),
    ],
  },
  {
    id: "sea", icon: "Waves",
    name: w("Sea", "Mer", "Meer"),
    words: [
      w("Octopus", "Pieuvre", "Krake"), w("Whale", "Baleine", "Wal"), w("Jellyfish", "Méduse", "Qualle"), w("Starfish", "Étoile de mer", "Seestern"),
      w("Crab", "Crabe", "Krabbe"), w("Seahorse", "Hippocampe", "Seepferdchen"), w("Seal", "Phoque", "Robbe"), w("Walrus", "Morse", "Walross"),
      w("Seagull", "Mouette", "Möwe"), w("Lobster", "Homard", "Hummer"), w("Shell", "Coquillage", "Muschel"), w("Coral reef", "Récif de corail", "Korallenriff"),
      w("Pearl", "Perle", "Perle"), w("Oyster", "Huître", "Auster"), w("Clownfish", "Poisson-clown", "Clownfisch"), w("Stingray", "Raie", "Rochen"),
      w("Sea urchin", "Oursin", "Seeigel"), w("Seaweed", "Algue", "Alge"), w("Wave", "Vague", "Welle"), w("Tide", "Marée", "Gezeiten"),
      w("Anchor", "Ancre", "Anker"), w("Shipwreck", "Épave", "Schiffswrack"), w("Snorkel mask", "Masque de plongée", "Tauchmaske"), w("Diver", "Plongeur", "Taucher"),
      w("Squid", "Calamar", "Kalmar"), w("Sandcastle", "Château de sable", "Sandburg"), w("Buoy", "Bouée", "Boje"), w("Life jacket", "Gilet de sauvetage", "Schwimmweste"),
      w("Fishing net", "Filet de pêche", "Fischernetz"), w("Sailor", "Marin", "Matrose"), w("Captain", "Capitaine", "Kapitän"), w("Message in a bottle", "Bouteille à la mer", "Flaschenpost"),
      w("Tsunami", "Tsunami", "Tsunami"), w("Orca", "Orque", "Orca"), w("Swordfish", "Espadon", "Schwertfisch"), w("Pufferfish", "Poisson-globe", "Kugelfisch"),
      w("Deckchair", "Chaise longue", "Liegestuhl"), w("Pelican", "Pélican", "Pelikan"), w("Flippers", "Palmes", "Taucherflossen"), w("Narwhal", "Narval", "Narwal"),
    ],
  },
  {
    id: "space", icon: "Rocket",
    name: w("Space", "Espace", "Weltall"),
    words: [
      w("Moon", "Lune", "Mond"), w("Planet", "Planète", "Planet"), w("Star", "Étoile", "Stern"), w("Mars", "Mars", "Mars"),
      w("Saturn", "Saturne", "Saturn"), w("Jupiter", "Jupiter", "Jupiter"), w("Earth", "Terre", "Erde"), w("Comet", "Comète", "Komet"),
      w("Meteorite", "Météorite", "Meteorit"), w("Asteroid", "Astéroïde", "Asteroid"), w("Black hole", "Trou noir", "Schwarzes Loch"), w("Galaxy", "Galaxie", "Galaxie"),
      w("Milky Way", "Voie lactée", "Milchstrasse"), w("Telescope", "Télescope", "Teleskop"), w("Satellite", "Satellite", "Satellit"), w("Space station", "Station spatiale", "Raumstation"),
      w("Spacesuit", "Combinaison spatiale", "Raumanzug"), w("UFO", "OVNI", "UFO"), w("Shooting star", "Étoile filante", "Sternschnuppe"), w("Crater", "Cratère", "Krater"),
      w("Solar eclipse", "Éclipse solaire", "Sonnenfinsternis"), w("Constellation", "Constellation", "Sternbild"), w("Big Dipper", "Grande Ourse", "Grosser Wagen"), w("Moon landing", "Alunissage", "Mondlandung"),
      w("Launch pad", "Pas de tir", "Startrampe"), w("Countdown", "Compte à rebours", "Countdown"), w("Space shuttle", "Navette spatiale", "Raumfähre"), w("Solar panel", "Panneau solaire", "Solarpanel"),
      w("Observatory", "Observatoire", "Sternwarte"), w("Neptune", "Neptune", "Neptun"), w("Venus", "Vénus", "Venus"), w("Pluto", "Pluton", "Pluto"),
      w("Supernova", "Supernova", "Supernova"), w("Planetarium", "Planétarium", "Planetarium"), w("Space probe", "Sonde spatiale", "Raumsonde"), w("Mission control", "Centre de contrôle", "Kontrollzentrum"),
      w("Jetpack", "Jetpack", "Jetpack"), w("Mercury", "Mercure", "Merkur"), w("Orbit", "Orbite", "Umlaufbahn"), w("Laser", "Laser", "Laser"),
    ],
  },
  {
    id: "farm", icon: "Tractor",
    name: w("Farm", "Ferme", "Bauernhof"),
    words: [
      w("Pig", "Cochon", "Schwein"), w("Sheep", "Mouton", "Schaf"), w("Goat", "Chèvre", "Ziege"), w("Horse", "Cheval", "Pferd"),
      w("Donkey", "Âne", "Esel"), w("Hen", "Poule", "Huhn"), w("Rooster", "Coq", "Hahn"), w("Duck", "Canard", "Ente"),
      w("Goose", "Oie", "Gans"), w("Turkey", "Dinde", "Truthahn"), w("Calf", "Veau", "Kalb"), w("Lamb", "Agneau", "Lamm"),
      w("Barn", "Grange", "Scheune"), w("Stable", "Écurie", "Stall"), w("Haystack", "Botte de foin", "Heuhaufen"), w("Pitchfork", "Fourche", "Heugabel"),
      w("Scarecrow", "Épouvantail", "Vogelscheuche"), w("Milk churn", "Bidon de lait", "Milchkanne"), w("Chicken coop", "Poulailler", "Hühnerstall"), w("Pigsty", "Porcherie", "Schweinestall"),
      w("Beehive", "Ruche", "Bienenstock"), w("Wheat", "Blé", "Weizen"), w("Silo", "Silo", "Silo"), w("Manure", "Fumier", "Mist"),
      w("Mud", "Boue", "Schlamm"), w("Combine harvester", "Moissonneuse-batteuse", "Mähdrescher"), w("Plough", "Charrue", "Pflug"), w("Fence", "Clôture", "Zaun"),
      w("Feeding trough", "Mangeoire", "Futterkrippe"), w("Wool", "Laine", "Wolle"), w("Milk", "Lait", "Milch"), w("Farm shop", "Magasin à la ferme", "Hofladen"),
      w("Horseshoe", "Fer à cheval", "Hufeisen"), w("Saddle", "Selle", "Sattel"), w("Rabbit hutch", "Clapier", "Kaninchenstall"), w("Orchard", "Verger", "Obstgarten"),
      w("Vineyard", "Vignoble", "Weinberg"), w("Cheese dairy", "Fromagerie", "Käserei"), w("Straw", "Paille", "Stroh"), w("Llama", "Lama", "Lama"),
    ],
  },
  {
    id: "party", icon: "PartyPopper",
    name: w("Party & holidays", "Fêtes", "Feste & Feiertage"),
    words: [
      w("Balloon", "Ballon de baudruche", "Ballon"), w("Confetti", "Confettis", "Konfetti"), w("Present", "Cadeau", "Geschenk"), w("Piñata", "Piñata", "Piñata"),
      w("Fireworks", "Feux d'artifice", "Feuerwerk"), w("Costume party", "Soirée déguisée", "Kostümparty"), w("Mask", "Masque", "Maske"), w("Party hat", "Chapeau pointu", "Partyhut"),
      w("Invitation", "Invitation", "Einladung"), w("Disco ball", "Boule à facettes", "Discokugel"), w("Dance floor", "Piste de danse", "Tanzfläche"), w("Buffet", "Buffet", "Buffet"),
      w("Lemonade", "Limonade", "Limonade"), w("Garland", "Guirlande", "Girlande"), w("Sparkler", "Cierge magique", "Wunderkerze"), w("Christmas tree", "Sapin de Noël", "Weihnachtsbaum"),
      w("Easter egg", "Œuf de Pâques", "Osterei"), w("Jack-o'-lantern", "Citrouille d'Halloween", "Kürbislaterne"), w("Santa Claus", "Père Noël", "Samichlaus"), w("Easter bunny", "Lapin de Pâques", "Osterhase"),
      w("Wedding", "Mariage", "Hochzeit"), w("New Year's Eve", "Saint-Sylvestre", "Silvester"), w("Champagne", "Champagne", "Champagner"), w("Musical chairs", "Chaises musicales", "Reise nach Jerusalem"),
      w("Treasure hunt", "Chasse au trésor", "Schatzsuche"), w("Hide and seek", "Cache-cache", "Versteckis"), w("Photo booth", "Photomaton", "Fotobox"), w("Chips", "Chips", "Chips"),
      w("Barbecue", "Barbecue", "Grill"), w("Gift wrap", "Papier cadeau", "Geschenkpapier"), w("Bouncy castle", "Château gonflable", "Hüpfburg"), w("Candy", "Bonbon", "Bonbon"),
      w("Cotton candy", "Barbe à papa", "Zuckerwatte"), w("Surprise party", "Fête surprise", "Überraschungsparty"), w("Cupcake", "Cupcake", "Cupcake"), w("Cocktail", "Cocktail", "Cocktail"),
      w("Advent calendar", "Calendrier de l'Avent", "Adventskalender"), w("Lollipop", "Sucette", "Lutscher"), w("Bonfire", "Feu de camp", "Lagerfeuer"), w("Birthday card", "Carte d'anniversaire", "Geburtstagskarte"),
    ],
  },
  {
    id: "tools", icon: "Wrench",
    name: w("Tools", "Outils", "Werkzeug"),
    words: [
      w("Hammer", "Marteau", "Hammer"), w("Screwdriver", "Tournevis", "Schraubenzieher"), w("Wrench", "Clé à molette", "Schraubenschlüssel"), w("Saw", "Scie", "Säge"),
      w("Drill", "Perceuse", "Bohrmaschine"), w("Nail", "Clou", "Nagel"), w("Screw", "Vis", "Schraube"), w("Pliers", "Pince", "Zange"),
      w("Tape measure", "Mètre ruban", "Massband"), w("Spirit level", "Niveau à bulle", "Wasserwaage"), w("Toolbox", "Boîte à outils", "Werkzeugkasten"), w("Workbench", "Établi", "Werkbank"),
      w("Axe", "Hache", "Axt"), w("Chainsaw", "Tronçonneuse", "Motorsäge"), w("Sandpaper", "Papier de verre", "Schleifpapier"), w("Paint roller", "Rouleau de peinture", "Farbroller"),
      w("Glue gun", "Pistolet à colle", "Heissklebepistole"), w("Duct tape", "Ruban adhésif", "Klebeband"), w("Safety goggles", "Lunettes de protection", "Schutzbrille"), w("Wheelbarrow", "Brouette", "Schubkarre"),
      w("Shovel", "Pelle", "Schaufel"), w("Rake", "Râteau", "Rechen"), w("Crowbar", "Pied-de-biche", "Brecheisen"), w("Vice", "Étau", "Schraubstock"),
      w("Chisel", "Ciseau à bois", "Meissel"), w("Soldering iron", "Fer à souder", "Lötkolben"), w("Extension cord", "Rallonge", "Verlängerungskabel"), w("Magnet", "Aimant", "Magnet"),
      w("Cable tie", "Serre-câble", "Kabelbinder"), w("Trowel", "Truelle", "Maurerkelle"), w("Cement mixer", "Bétonnière", "Betonmischer"), w("Jackhammer", "Marteau-piqueur", "Presslufthammer"),
      w("Hard hat", "Casque de chantier", "Bauhelm"), w("Allen key", "Clé Allen", "Inbusschlüssel"), w("Plunger", "Ventouse", "Saugglocke"), w("Garden hose", "Tuyau d'arrosage", "Gartenschlauch"),
      w("Watering can", "Arrosoir", "Giesskanne"), w("Lawn mower", "Tondeuse", "Rasenmäher"), w("Pruning shears", "Sécateur", "Gartenschere"), w("Pickaxe", "Pioche", "Spitzhacke"),
    ],
  },
];
